# Generated by Django 5.0.7 on 2024-07-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Studentship', 'Studentship'), ('EOPEP', 'Eopep Examinations'), ('EXAMS', 'Examinations')], default='Studentship', max_length=15),
        ),
    ]
