# Generated by Django 5.0.7 on 2024-07-18 12:31

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstudent',
            name='major',
            field=models.CharField(choices=dashboard.models.EnrolledStudent.get_majors, max_length=100),
        ),
    ]
