# Generated by Django 5.0.7 on 2024-07-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_enrolledstudent_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstudent',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.major'),
        ),
    ]
