# Generated by Django 5.0.7 on 2024-07-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_enrolledstudent_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
