# Generated by Django 5.0.7 on 2024-07-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooluser',
            name='age',
        ),
    ]
