# Generated by Django 5.0.7 on 2024-08-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_schooluser_age'),
        ('dashboard', '0001_initial'),
        ('exercises', '0004_alter_exercise_for_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstudent',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.major'),
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
