# Generated by Django 5.0.7 on 2024-07-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_schooluser_age_schooluser_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
    ]
