# Generated by Django 5.0.7 on 2024-07-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_schooluser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='birthdate',
            field=models.DateField(null=True, unique_for_year=True),
        ),
    ]
