# Generated by Django 5.0.7 on 2024-07-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_schooluser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
