# Generated by Django 5.0.7 on 2024-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_schooluser_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='age',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
