# Generated by Django 5.0.7 on 2024-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_schooluser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='age',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
    ]
