# Generated by Django 5.0.7 on 2024-07-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_schooluser_age_alter_schooluser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
