# Generated by Django 5.0.7 on 2024-07-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_schooluser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
