# Generated by Django 5.0.7 on 2024-07-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_schooluser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
