# Generated by Django 5.0.7 on 2024-07-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_schooluser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
