# Generated by Django 5.0.7 on 2024-07-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_schooluser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='id',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
