# Generated by Django 5.0.7 on 2024-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_schooluser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
