# Generated by Django 5.0.7 on 2024-07-23 08:16

import django.db.models.deletion
import exercises.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='uploaded_files',
            field=models.FileField(upload_to='exercises/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.CreateModel(
            name='SubmittedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.FileField(upload_to=exercises.models.uploadPath)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
