# Generated by Django 5.0.7 on 2024-08-01 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='for_students',
            field=models.ManyToManyField(limit_choices_to={'role': 'Student'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
