# Generated by Django 5.0.7 on 2024-07-23 08:17

import exercises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_uploaded_files_submittedexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedexercise',
            name='typed_answer',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='submittedexercise',
            name='student_answer',
            field=models.FileField(blank=True, null=True, upload_to=exercises.models.uploadPath),
        ),
    ]
