# Generated by Django 5.0.7 on 2024-08-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('exercises', '0003_alter_exercise_deadline_alter_exercise_for_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='for_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.major'),
        ),
    ]
