# Generated by Django 5.0.7 on 2024-07-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_submittedexercise_typed_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedexercise',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='submittedexercise',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
